language: java
sudo: false
branches:
  except:
    - legacy
    - experimental
node_js:
  - '6.9.5'
cache:
  directories:
     - ./node_modules
before_script:
  - npm install
  - npm install -g gulp
  - npm install -g gulp-conventional-changelog
  - npm install -g gulp-cli
script: gulp changelog